package com.G2T8.CS203WebApp.service;

import com.G2T8.CS203WebApp.repository.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.G2T8.CS203WebApp.model.*;
import java.util.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Service
public class CovidHistoryService {

    @Autowired
    private CovidHistoryRepository covidHistoryRepository;

    public List<CovidHistory> getAllCovidHistories() {
        return covidHistoryRepository.findAll();
    }

    // returns list because one person can contract covid several times
    public List<CovidHistory> getAllCovidHistoryFromOneUser(Long ID) {

        // getting the covid history of each user by custom query findByUserId in CovidHistoryRepo
        // do not use findById bc that uses CovidHistoryId which does dont point to
        // which user it is referring to

        List<CovidHistory> origList = covidHistoryRepository.findByUserId(ID);
        return origList; 

    }

    // returns a particular covidHistory record of one user
    public CovidHistory getOneCovidHistoryFromOneUser(Long ID, LocalDateTime contracteddate){
        List<CovidHistory> answer = covidHistoryRepository.findByUserId(ID);
        LocalDate contractdatewithoutime = contracteddate.toLocalDate(); 
        for(int i = 0 ; i<= answer.size()-1 ; i++){
            if(answer.get(i).getContractedDate().toLocalDate().equals(contractdatewithoutime)){
                return answer.get(i);
            }
        }

        return null; 

    }


    // recovery date is can be null , so can add in covidhistory with just userid, 
    //covidHistoryID (autogenerated), contracted_date 
    public CovidHistory addCovidHistory(CovidHistory covidHistory) {
        return covidHistoryRepository.save(covidHistory);
    }

    // after recovery date is known , can use this method to add in recoverDate
    public CovidHistory addRecoveryDate(Long ID, LocalDateTime contracteddate){
        List<CovidHistory> answer = covidHistoryRepository.findByUserId(ID);
        LocalDate contractdatewithoutime = contracteddate.toLocalDate();
        for (int i = 0; i <= answer.size() - 1; i++) {
            if (answer.get(i).getContractedDate().toLocalDate().equals(contractdatewithoutime)) {
                return answer.get(i);
            }
        }
        return null;

    
    }
    
}
