package com.G2T8.CS203WebApp.service;

import com.G2T8.CS203WebApp.repository.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.G2T8.CS203WebApp.model.*;
import java.util.*;
import java.time.LocalDateTime;

@Service
public class CovidHistoryService {

    @Autowired
    private CovidHistoryRepository covidHistoryRepository;

    // ---done-----
    public List<CovidHistory> getAllCovidHistories() {
        return covidHistoryRepository.findAll();
    }

    // ---done-----
    // returns list because one person can contract covid several times
    public List<CovidHistory> getAllCovidHistoryFromOneUser(Long ID) {

        // getting the covid history of each user by custom query findByUserId in CovidHistoryRepo
        // do not use findById bc that uses CovidHistoryId which does dont point to
        // which user it is referring to

        List<Optional<CovidHistory>> origList = covidHistoryRepository.findByUserId(ID);
        List<CovidHistory> toReturn = new ArrayList<>();

        if(origList != null){
            for (int i = 0; i <= origList.size() - 1; i++) {
                if (origList.get(i).isPresent()) {
                    Optional<CovidHistory> opCovidHis = origList.get(i);
                    CovidHistory covidHis = opCovidHis.get();
                    toReturn.add(covidHis);

                } else {
                    continue;
                }

            }
            return toReturn;

        }
        return null; 

    }

    // -- done -- 
    // returns a particular covidHistory record of one user
    public CovidHistory getOneCovidHistoryFromOneUser(Long ID, LocalDateTime contracteddate){
        Optional<CovidHistory> temp = covidHistoryRepository.findByUserIdAndContractedDate(ID, contracteddate);
        if (temp.isPresent()) {
            CovidHistory toReturn = temp.get();
            return toReturn;

        }
        return null; 

    }


    // recovery date is can be null , so can add in covidhistory with just userid, 
    //covidHistoryID (autogenerated), contracted_date 
    public CovidHistory addCovidHistory(CovidHistory covidHistory) {
        return covidHistoryRepository.save(covidHistory);
    }

    // after recovery date is known , can use this method to add in recoverDate
    public CovidHistory addRecoveryDate(CovidHistory covidHistory){
        return covidHistoryRepository.save(covidHistory); 
    }
    
}
